language: python

python:
  - '3.6'

install:
  - pip install -q -r requirements-dev.txt .

script:
  - coverage run --source "$(basename "$PWD")" setup.py test

notifications:
  email: false
deploy:
  provider: pypi
  user: ahuigo
  password:
    secure: RdASA7x8N5Js2Lm2ELbyQOYb/hiUF5zM17tZKciwNw6AXSxOTwOXlTgg9lUOXLoIs2VLxz51CyuuQRwRwjwfwOkD6Zx/6MnMwGt6jKVNbsurHjCKrxEtFrFTySA012ZqYSejvJDjdNSYs3DY+rdlKcT31NVEB2gShq7OPes+gWw7i6SEy3xZZI/DM9l4KOFHAobVTPtwijf1WphThkScMnR9Cblh2+6lYyfy4xwNYy/YuSkPvADryRdyDNfWZg17m4uH/UzUznBxYBbmmDLeh5hnDgmaA1xm+M6OpHdjV0ZaFkFbJx+kkq5pxnpJ2cf9UkaUIT6kPdJObwg/vCk1uY6JSXYAGa0tdlQFhN97UULTDDVy4bcsuWCRr+3FyF5Q9uXStTCAJ06N508wExowlAjULFrsiTHY/LCleaH1K3s+/qFglJXJRxvboBnwaQOG4/Tpi5sNYc3BfuOlcyioeFJKz/IVRUpAmpKwgP0/oeg9PeUViTYHJEXImdW7U9J0WR2DE/syBQbgapZcZAcFMQqokn34N/vKGgKmCxyBj5uuqNU7LCb13hed7j1Czjb9mqsY12mnek46zZPyoHd0wiHDOMW8kFnmJaguTgNRvc6d4JHT0/o7mNAZXKxd7YOb2Vd3pPIhn1u3goqrLk3zxBhyqQ4ah07V+pyJlrnHf7U=
